version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: golang:1.18.5-alpine3.16
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ROLE_ARN: arn:aws:iam::144291977149:role/circleci-oidc
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: |
            apk update
            apk add docker
            apk add jq
            apk add curl
            apk add git
            apk add --no-cache \
            python3 \
            py3-pip \
            && pip3 install --upgrade pip \
            && pip3 install --no-cache-dir \
            awscli \
            && rm -rf /var/cache/apk/*         
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          # paths:
          #   - /caches/app.tar
      # - run:
      #     name: Make Dummy Docker Compse File
      #     command: |
      #       touch ././docker-compose.yml
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      # - run:
      #     name: Run tests
      #     command: |
      #       echo docker-compose -f ./docker-compose.test.yml >> ./docker-compose.test.yml
      #       docker-compose -f ./docker-compose.test.yml up
      - run: echo "Uploading Image Now"
      # - snyk/scan:
      #     docker-image-name: app --severity-threshold=high     || true
      #     fail-on-issues: true
      #     install-alpine-dependencies: true
      - deploy:
          name: Push application Docker image
          command: |
            GIT_COMMIT_ID=$(git rev-parse --short HEAD)
            eval "$(aws sts assume-role-with-web-identity --role-arn $AWS_ROLE_ARN --role-session-name "${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}" --web-identity-token "${CIRCLE_OIDC_TOKEN}" --duration-seconds 3600 | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\n"')"
            aws sts get-caller-identity
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR
            docker tag app $ECR/go-test:$CIRCLE_BUILD_NUM
            docker tag app $ECR/go-test:$CIRCLE_SHA1
            docker tag app $ECR/go-test:git-$GIT_COMMIT_ID
            docker push $ECR/go-test:$CIRCLE_BUILD_NUM
            docker push $ECR/go-test:$CIRCLE_SHA1
            docker push $ECR/go-test:git-$GIT_COMMIT_ID
           

          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context:
            - guac
